---
global:
  cloudHsm:
    enabled: true
    ip: "10.101.29.134"

egressSafelist:
- name: sqs
  service:
    hosts:
      - "sqs.eu-west-2.amazonaws.com"
      - "eu-west-2.queue.amazonaws.com"
    ports:
    - name: https
      number: 443
      protocol: TLS
    location: MESH_EXTERNAL
    resolution: DNS
- name: rds
  service:
    hosts: ["*.eu-west-2.rds.amazonaws.com"]
    addresses: ["10.0.0.0/8"]
    ports:
    - name: aurora
      number: 3306
      protocol: TCP
    location: MESH_EXTERNAL
    resolution: NONE
- name: verify-connector-sandbox
  service:
    hosts: ["test-connector.london.sandbox.govsvc.uk"]
    ports:
    - name: https
      number: 443
      protocol: TLS
    location: MESH_EXTERNAL
    resolution: DNS
- name: verify-integration-connector-sandbox
  service:
    hosts: ["test-integration-connector.london.sandbox.govsvc.uk"]
    ports:
    - name: https
      number: 443
      protocol: TLS
    location: MESH_EXTERNAL
    resolution: DNS
- name: verify-hub-integration
  service:
    hosts: ["www.integration.signin.service.gov.uk"]
    ports:
    - name: https
      number: 443
      protocol: TLS
    location: MESH_EXTERNAL
    resolution: DNS

namespaces:
- name: sandbox-connector-node-metadata
  owner: alphagov
  repository: verify-metadata
  branch: sandbox
  path: ci/sandbox
  requiredApprovalCount: 0
- name: sandbox-main
- name: sandbox-metadata-controller
  owner: alphagov
  repository: verify-metadata-controller
  branch: sandbox
  path: ci/sandbox
  requiredApprovalCount: 0
  scope: cluster
  talksToHsm: true
- name: sandbox-proxy-node-dev
  owner: alphagov
  repository: verify-proxy-node
  branch: sandbox
  path: ci/sandbox
  requiredApprovalCount: 0
  talksToHsm: true
- name: spike-dcs-mtls
- name: sandbox-gsp-service-operator-test
