---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: test
spec:
  releaseName: test
  chart:
    git: "https://github.com/alphagov/verify-eidas-deployment.git"
    ref: "eks-prep"
    path: "."
  values:
    global:
      cluster:
        name: "{{ .Values.global.cluster.name }}"
        domain: "{{ .Values.global.cluster.domain }}"
    stubConnector:
      enabled: true
    vmc:
      secretName: verify-staging-vmc
    vsp:
      secretName: verify-staging-test-vsp
