---
apiVersion: concourse.k8s.io/v1beta1
kind: Team
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: metadata-controller
spec:
  roles:
  - name: owner
    github:
      teams: ["alphagov:re-gsp"]
    local:
      users: ["pipeline-operator"]
  - name: pipeline-operator
    local:
      users: ["visitor"]
