terraform_source: &terraform_source
  env_name: ((account-name))
  backend_type: s3
  backend_config: &terraform_backend_config
    bucket: cd-gsp-private-qndvvc
    region: eu-west-2
  vars: &terraform_vars
    aws_account_role_arn: ((account-role-arn))
    public-gpg-keys: "W10=" # echo -n "[]" | base64
    promotion_signing_key: ((ci-system-gpg-private))
    promotion_verification_key: ((ci-system-gpg-public))
    github_client_id: PLACEHOLDER
    github_client_secret: PLACEHOLDER
task_image_resource: &task_image_resource
  type: docker-image
  source: {repository: "govsvc/task-toolbox", tag: "1.0.0"}
apply_addons_task: &apply_addons_task
  platform: linux
  image_resource: *task_image_resource
  params: &apply_addons_task_params
    ACCOUNT_ROLE_ARN: ((account-role-arn))
    ACCOUNT_NAME: ((account-name))
    CLUSTER_NAME: ((cluster-name))
    TERRAFORM_BUCKET: cd-gsp-private-qndvvc
    TERRAFORM_REGION: eu-west-2
    TF_VAR_aws_account_role_arn: ((account-role-arn))
    TF_VAR_splunk_hec_token: PLACEHOLDER
    TF_VAR_splunk_hec_url: ((splunk_hec_url))
    TF_VAR_promotion_signing_key: ((ci-system-gpg-private))
    TF_VAR_promotion_verification_key: ((ci-system-gpg-public))
    TF_VAR_github_client_id: PLACEHOLDER
    TF_VAR_github_client_secret: PLACEHOLDER
  run:
    path: /bin/bash
    args:
    - -eu
    - -c
    - |
      echo "fetching kubeconfig from terraform state..."
      jq -r '."kubeconfig"' cluster-outputs/metadata > kubeconfig
      export KUBECONFIG=$(pwd)/kubeconfig
      echo "generating kubeyaml addons with terraform..."
      cd "gsp-teams/terraform/accounts/${ACCOUNT_NAME}/clusters/${CLUSTER_NAME}"
      terraform init \
        -backend-config="bucket=${TERRAFORM_BUCKET}" \
        -backend-config="key=${ACCOUNT_NAME}/clusters/${CLUSTER_NAME}.tfstate" \
        -backend-config="region=${TERRAFORM_REGION}" \
        -backend=true \
        -force-copy \
        -get=true \
        -input=false
      terraform workspace select "${ACCOUNT_NAME}"
      terraform apply -var "public-gpg-keys=$(yq . ../../../users/*.yaml | jq -s '[.[] | select(.teams[] | IN("re-gsp")) | .pub]' | base64)" -auto-approve
      echo "applying kubeyaml..."
      eval $(aws-assume-role $ACCOUNT_ROLE_ARN)
      until kubectl apply -R -f addons/; do
        echo "apply failed retrying..."
        sleep 1
      done
      function not_running_count() {
        kubectl get pods -o json --all-namespaces | jq -r '.items[].status.phase' | grep -v Running | grep -v Completed | wc -l | awk '{ print $1 }'
      }
      sleep 30s
      while [[ "$(not_running_count)" != "0" ]]; do
        echo "waiting for $(not_running_count) pods to start"
        sleep 3
      done
      kubectl get pods --all-namespaces
  inputs:
  - name: cluster-outputs
  - name: gsp-teams
drain_cluster_task: &drain_cluster_task
  platform: linux
  image_resource: *task_image_resource
  params: &drain_cluster_task_params
    ACCOUNT_ROLE_ARN: ((account-role-arn))
    AWS_REGION: eu-west-2
    AWS_DEFAULT_REGION: eu-west-2
    CLUSTER_NAME: drb-eks-test
  run:
    path: /bin/bash
    args:
    - -eu
    - -c
    - |
      eval $(aws-assume-role $ACCOUNT_ROLE_ARN)
      echo "fetching kubeconfig from AWS..."
      aws eks update-kubeconfig --name drb-eks-test --kubeconfig ./kubeconfig
      export KUBECONFIG=$(pwd)/kubeconfig

      CLUSTER_ASGS=$(aws autoscaling describe-auto-scaling-groups | jq -r ".AutoScalingGroups[] | select( .Tags[].Key == \"kubernetes.io/cluster/${CLUSTER_NAME}\")" | jq -r .AutoScalingGroupName)
      for ASG_NAME in $CLUSTER_ASGS; do

        echo "scaling $ASG_NAME to zero"
        aws autoscaling update-auto-scaling-group --auto-scaling-group-name "${ASG_NAME}" --min-size 0 --max-size 0 --desired-capacity 0

        echo "fetching number of instances remaining in $ASG_NAME"
        INSTANCES=$(aws autoscaling describe-auto-scaling-groups --auto-scaling-group-names "$ASG_NAME" --query "AutoScalingGroups[0].Instances[*].InstanceId" --output text)

        if [ ! -z "$INSTANCES" ]; then
          echo "waiting for following instances to terminate in $ASG_NAME: $INSTANCES"
          aws ec2 wait instance-terminated --instance-ids $INSTANCES
          echo "$INSTANCES instances removed from $ASG_NAME"
        fi

      done

      echo "deleting all namespaces..."
      # this will always error, due to "kube-system" and "default" being protected namespaces
      kubectl delete namespace --all || true
      function terminating_count() {
        kubectl get pods -o json --all-namespaces | jq -r '.items[].status.phase' | grep Terminating | wc -l | awk '{ print $1 }'
      }
      sleep 30s
      while [[ "$(terminating_count)" != "0" ]]; do
        echo "waiting for $(terminating_count) pods to terminate"
        sleep 3
      done
      kubectl get pods --all-namespaces
  inputs:
  - name: cluster-outputs
  - name: gsp-teams

resource_types:
- name: terraform
  type: docker-image
  source:
    repository: govsvc/terraform-resource
    tag: 0.13.0-beta.2
- name: github
  type: docker-image
  source:
    repository: "govsvc/concourse-github-resource"
    tag: "0.0.1551114195"

resources:
- name: gsp-teams
  type: git
  source:
    uri: https://github.com/alphagov/gsp-teams.git
    organization: alphagov
    repository: gsp-teams
    github_api_token: "((github-api-token))"
    approvers:
      - "samcrang"
      - "paroxp"
      - "chrisfarms"
      - "tlwr"
      - "blairboy362"
    required_approval_count: 2
    branch: eks-firebreak
    commit_verification_keys: ((public-gpg-keys))
- name: persistent
  type: terraform
  source:
    <<: *terraform_source
    backend_config:
      <<: *terraform_backend_config
      key: ((account-name))/clusters/((cluster-name))-persistent.tfstate
    vars:
      <<: *terraform_vars
      splunk_hec_token: PLACEHOLDER
      splunk_hec_url: ((splunk_hec_url))
- name: cluster
  type: terraform
  source:
    <<: *terraform_source
    backend_config:
      <<: *terraform_backend_config
      key: ((account-name))/clusters/((cluster-name)).tfstate
    vars:
      <<: *terraform_vars
      persistent_state_bucket_name: cd-gsp-private-qndvvc
      persistent_state_bucket_key: ((account-name))/clusters/((cluster-name))-persistent.tfstate
      splunk_hec_token: PLACEHOLDER
      splunk_hec_url: ((splunk_hec_url))

jobs:
- name: terraform
  serial: true
  plan:
  - get: gsp-teams
    trigger: true
  - put: persistent
    params:
      env_name: ((account-name))
      terraform_source: gsp-teams/terraform/accounts/((account-name))/persistent/((cluster-name))/
  - put: cluster
    params:
      env_name: ((account-name))
      terraform_source: gsp-teams/terraform/accounts/((account-name))/clusters/((cluster-name))/
- name: apply-addons-tools-cluster
  serial: true
  plan:
  - get: gsp-teams
    trigger: true
    passed: ["terraform"]
  - get: cluster
    passed: ["terraform"]
  - task: apply-addons
    timeout: 30m
    config:
      <<: *apply_addons_task
      params:
        <<: *apply_addons_task_params
        TF_VAR_persistent_state_bucket_name: cd-gsp-private-qndvvc
        TF_VAR_persistent_state_bucket_key: ((account-name))/clusters/((cluster-name))-persistent.tfstate
    input_mapping: {cluster-outputs: cluster}
- name: destroy-cluster
  serial: true
  plan:
  - get: gsp-teams
  - get: cluster
  - task: drain-cluster
    timeout: 30m
    config:
      <<: *drain_cluster_task
      params:
        <<: *drain_cluster_task_params
        TF_VAR_persistent_state_bucket_name: cd-gsp-private-qndvvc
        TF_VAR_persistent_state_bucket_key: ((account-name))/clusters/((cluster-name))-persistent.tfstate
    input_mapping: {cluster-outputs: cluster}
  - put: cluster
    params:
      env_name: ((account-name))
      terraform_source: gsp-teams/terraform/accounts/((account-name))/clusters/((cluster-name))/
      action: destroy
    get_params:
      action: destroy
- name: destroy-persistent
  serial: true
  plan:
  - get: gsp-teams
  - get: persistent
  - put: persistent
    params:
      action: destroy
      env_name: run-sandbox
      terraform_source: gsp-teams/terraform/accounts/run-sandbox/persistent/drb-eks-test.run-sandbox.aws.ext.govsandbox.uk/
    get_params:
      action: destroy
