groups:
- name: provision
  jobs:
  - terraform
  - apply-addons-tools-cluster
  - apply-addons-staging-cluster
- name: bootstrap
  jobs:
  - bootstrap-tools-cluster
  - bootstrap-staging-cluster
- name: destroy
  jobs:
  - destroy-tools-cluster
  - destroy-staging-cluster



task_image_resource: &task_image_resource
  type: docker-image
  source: {repository: "govsvc/task-toolbox", tag: "1.0.0"}


apply_addons_task: &apply_addons_task
  platform: linux
  image_resource: *task_image_resource
  params: &apply_addons_task_params
    ACCOUNT_ROLE_ARN: ((account-role-arn))
    ACCOUNT_NAME: ((account-name))
    CLUSTER_NAME:
    TERRAFORM_BUCKET: cd-gsp-private-qndvvc
    TERRAFORM_REGION: eu-west-2
    TF_VAR_aws_account_role_arn: ((account-role-arn))
    TF_VAR_splunk_hec_token: ((splunk_hec_token))
    TF_VAR_splunk_hec_url: ((splunk_hec_url))
    TF_VAR_promotion_signing_key: ((ci-system-gpg-private))
    TF_VAR_promotion_verification_key: ((ci-system-gpg-public))
    TF_VAR_github_client_id: ((github-client-id))
    TF_VAR_github_client_secret: ((github-client-secret))
  run:
    path: /bin/bash
    args:
    - -eu
    - -c
    - |
      echo "fetching kubeconfig from terraform state..."
      jq -r '."admin-kubeconfig"' cluster-outputs/metadata > kubeconfig
      export KUBECONFIG=$(pwd)/kubeconfig
      echo "generating kubeyaml addons with terraform..."
      cd "gsp-teams/terraform/accounts/${ACCOUNT_NAME}/clusters/${CLUSTER_NAME}"
      terraform init \
        -backend-config="bucket=${TERRAFORM_BUCKET}" \
        -backend-config="key=${ACCOUNT_NAME}/clusters/${CLUSTER_NAME}.tfstate" \
        -backend-config="region=${TERRAFORM_REGION}" \
        -backend=true \
        -force-copy \
        -get=true \
        -input=false
      terraform workspace select "${ACCOUNT_NAME}"
      terraform apply -var "public-gpg-keys=$(yq . ../../../users/*.yaml | jq -s '[.[] | select(.teams[] | IN("verify-tech-team-eidas")) | .pub]' | base64)" -auto-approve
      echo "applying kubeyaml..."
      eval $(aws-assume-role $ACCOUNT_ROLE_ARN)
      until kubectl apply -R -f addons/; do
        echo "apply failed retrying..."
        sleep 1
      done
      function not_ready_count() {
        kubectl get pods -o json --all-namespaces | jq -r '.items[].status.conditions[].status' | grep False | wc -l | awk '{ print $1 }'
      }
      function not_running_count() {
        kubectl get pods -o json --all-namespaces | jq -r '.items[].status.phase' | grep -v Running | wc -l | awk '{ print $1 }'
      }
      sleep 30s
      while [[ "$(not_running_count)" != "0" ]]; do
        echo "waiting for $(not_running_count) pods to start"
        sleep 3
      done
      while [[ "$(not_ready_count)" != "0" ]]; do
        echo "waiting for $(not_ready_count) status probes to pass"
        sleep 3
      done
      kubectl get pods --all-namespaces
  inputs:
  - name: cluster-outputs
  - name: gsp-teams


wait_and_drain_bootstrapper: &wait_and_drain_bootstrapper
  platform: linux
  image_resource: *task_image_resource
  params:
    ACCOUNT_ROLE_ARN: ((account-role-arn))
  run:
    path: /bin/bash
    args:
    - -eu
    - -c
    - |
      eval $(aws-assume-role $ACCOUNT_ROLE_ARN)
      jq -r '."admin-kubeconfig"' cluster-outputs/metadata > kubeconfig
      export KUBECONFIG=$(pwd)/kubeconfig
      echo "Waiting for kubernetes..."
      sleep 30s
      until kubectl --kubeconfig kubeconfig -n kube-system get pods | grep kube-apiserver | grep -v bootstrap
      do
        echo -n "."
        sleep 5s
      done
      echo "Draining bootstrapper node"
      kubectl --kubeconfig kubeconfig drain --ignore-daemonsets --force --grace-period=60 -l 'node-role.kubernetes.io/bootstrapper'
  inputs:
  - name: cluster-outputs


destroy_bootstrapper: &destroy_bootstrapper
  platform: linux
  image_resource: *task_image_resource
  params:
    ACCOUNT_ROLE_ARN: ((account-role-arn))
  run:
    path: /bin/bash
    args:
    - -eu
    - -c
    - |
      eval $(aws-assume-role $ACCOUNT_ROLE_ARN)
      jq -r '."admin-kubeconfig"' cluster-outputs/metadata > kubeconfig
      export KUBECONFIG=$(pwd)/kubeconfig
      kubectl --kubeconfig kubeconfig delete node -l 'node-role.kubernetes.io/bootstrapper'
  inputs:
  - name: cluster-outputs






terraform_source: &terraform_source
  env_name: ((account-name))
  backend_type: s3
  backend_config: &terraform_backend_config
    bucket: cd-gsp-private-qndvvc
    region: eu-west-2
  vars: &terraform_vars
    aws_account_role_arn: ((account-role-arn))
    public-gpg-keys: "W10=" # echo -n "[]" | base64
    promotion_signing_key: ((ci-system-gpg-private))
    promotion_verification_key: ((ci-system-gpg-public))
    github_client_id: ((github-client-id))
    github_client_secret: ((github-client-secret))





resource_types:

- name: terraform
  type: docker-image
  source:
    repository: govsvc/terraform-resource
    tag: 0.13.0-beta.2

- name: github
  type: docker-image
  source:
    repository: "govsvc/concourse-github-resource"
    tag: "0.0.1551114195"



resources:

- name: gsp-teams
  type: github
  source:
    uri: https://github.com/alphagov/gsp-teams.git
    organization: alphagov
    repository: gsp-teams
    github_api_token: "((github-api-token))"
    approvers:
      - "samcrang"
      - "paroxp"
      - "chrisfarms"
      - "tlwr"
    required_approval_count: 2
    branch: master
    commit_verification_keys: ((public-gpg-keys))
- name: common-infra
  type: terraform
  source:
    <<: *terraform_source
    backend_config:
      <<: *terraform_backend_config
      key: ((account-name))/common.tfstate
- name: tools-persistent
  type: terraform
  source:
    <<: *terraform_source
    backend_config:
      <<: *terraform_backend_config
      key: ((account-name))/clusters/tools-persistent.tfstate
    vars:
      <<: *terraform_vars
      splunk_hec_token: ((splunk_hec_token))
      splunk_hec_url: ((splunk_hec_url))
- name: tools-cluster
  type: terraform
  source:
    <<: *terraform_source
    backend_config:
      <<: *terraform_backend_config
      key: ((account-name))/clusters/tools.tfstate
    vars:
      <<: *terraform_vars
      persistent_state_bucket_name: cd-gsp-private-qndvvc
      persistent_state_bucket_key: ((account-name))/clusters/tools-persistent.tfstate
- name: tools-cluster-bootstrapper
  type: terraform
  source:
    <<: *terraform_source
    backend_config:
      <<: *terraform_backend_config
      key: ((account-name))/clusters/tools-bootstrapper.tfstate
    vars:
      <<: *terraform_vars
      cluster_state_bucket_name: cd-gsp-private-qndvvc
      cluster_state_bucket_key: ((account-name))/clusters/tools.tfstate
- name: staging-persistent
  type: terraform
  source:
    <<: *terraform_source
    backend_config:
      <<: *terraform_backend_config
      key: ((account-name))/clusters/staging-persistent.tfstate
    vars:
      <<: *terraform_vars
      splunk_hec_token: ((splunk_hec_token))
      splunk_hec_url: ((splunk_hec_url))
- name: staging-cluster
  type: terraform
  source:
    <<: *terraform_source
    backend_config:
      <<: *terraform_backend_config
      key: ((account-name))/clusters/staging.tfstate
    vars:
      <<: *terraform_vars
      persistent_state_bucket_name: cd-gsp-private-qndvvc
      persistent_state_bucket_key: ((account-name))/clusters/staging-persistent.tfstate
      splunk_hec_token: ((splunk_hec_token))
      splunk_hec_url: ((splunk_hec_url))
- name: staging-cluster-bootstrapper
  type: terraform
  source:
    <<: *terraform_source
    backend_config:
      <<: *terraform_backend_config
      key: ((account-name))/clusters/staging-bootstrapper.tfstate
    vars:
      <<: *terraform_vars
      cluster_state_bucket_name: cd-gsp-private-qndvvc
      cluster_state_bucket_key: ((account-name))/clusters/staging.tfstate





jobs:

- name: terraform
  serial: true
  plan:
  - get: gsp-teams
    trigger: true
  - put: common-infra
    params:
      env_name: ((account-name))
      terraform_source: gsp-teams/terraform/accounts/((account-name))/
  - put: tools-persistent
    params:
      env_name: ((account-name))
      terraform_source: gsp-teams/terraform/accounts/((account-name))/persistent/tools/
  - put: staging-persistent
    params:
      env_name: ((account-name))
      terraform_source: gsp-teams/terraform/accounts/((account-name))/persistent/staging/
  - put: tools-cluster
    params:
      env_name: ((account-name))
      terraform_source: gsp-teams/terraform/accounts/((account-name))/clusters/tools/
  - put: staging-cluster
    params:
      env_name: ((account-name))
      terraform_source: gsp-teams/terraform/accounts/((account-name))/clusters/staging/

- name: bootstrap-tools-cluster
  serial: true
  plan:
  - get: gsp-teams
  - get: tools-cluster
  - put: tools-cluster-bootstrapper
    params:
      env_name: ((account-name))
      terraform_source: gsp-teams/terraform/accounts/((account-name))/bootstrapper/
  - task: wait-then-drain-bootstrapper-node
    input_mapping: {cluster-outputs: tools-cluster}
    config: *wait_and_drain_bootstrapper
  - put: tools-cluster-bootstrapper
    params:
      env_name: ((account-name))
      terraform_source: gsp-teams/terraform/accounts/((account-name))/bootstrapper/
      action: destroy
    get_params:
      action: destroy
  - task: delete-bootstrapper-node
    input_mapping: {cluster-outputs: tools-cluster}
    config: *destroy_bootstrapper
- name: bootstrap-staging-cluster
  serial: true
  plan:
  - get: gsp-teams
  - get: staging-cluster
  - put: staging-cluster-bootstrapper
    params:
      env_name: ((account-name))
      terraform_source: gsp-teams/terraform/accounts/((account-name))/bootstrapper/
  - task: wait-then-drain-bootstrapper-node
    input_mapping: {cluster-outputs: staging-cluster}
    config: *wait_and_drain_bootstrapper
  - put: staging-cluster-bootstrapper
    params:
      env_name: ((account-name))
      terraform_source: gsp-teams/terraform/accounts/((account-name))/bootstrapper/
      action: destroy
    get_params:
      action: destroy
  - task: delete-bootstrapper-node
    input_mapping: {cluster-outputs: staging-cluster}
    config: *destroy_bootstrapper

- name: apply-addons-tools-cluster
  serial: true
  plan:
  - get: gsp-teams
    trigger: true
    passed: ["terraform"]
  - get: tools-cluster
    passed: ["terraform"]
  - task: apply-addons
    timeout: 30m
    config:
      <<: *apply_addons_task
      params:
        <<: *apply_addons_task_params
        CLUSTER_NAME: tools
        TF_VAR_persistent_state_bucket_name: cd-gsp-private-qndvvc
        TF_VAR_persistent_state_bucket_key: ((account-name))/clusters/tools-persistent.tfstate
    input_mapping: {cluster-outputs: tools-cluster}
- name: apply-addons-staging-cluster
  serial: true
  plan:
  - get: gsp-teams
    trigger: true
    passed: ["terraform"]
  - get: staging-cluster
    passed: ["terraform"]
  - task: apply-addons
    timeout: 30m
    config:
      <<: *apply_addons_task
      params:
        <<: *apply_addons_task_params
        CLUSTER_NAME: staging
        TF_VAR_persistent_state_bucket_name: cd-gsp-private-qndvvc
        TF_VAR_persistent_state_bucket_key: ((account-name))/clusters/staging-persistent.tfstate
    input_mapping: {cluster-outputs: staging-cluster}

- name: destroy-tools-cluster
  serial: true
  plan:
  - get: gsp-teams
    passed: ["terraform"]
  - put: tools-cluster
    params:
      env_name: ((account-name))
      terraform_source: gsp-teams/terraform/accounts/((account-name))/clusters/tools/
      action: destroy
    get_params:
      action: destroy
- name: destroy-staging-cluster
  serial: true
  plan:
  - get: gsp-teams
    passed: ["terraform"]
  - put: staging-cluster
    params:
      env_name: ((account-name))
      terraform_source: gsp-teams/terraform/accounts/((account-name))/clusters/staging/
      action: destroy
    get_params:
      action: destroy
