---
jobs:
- name: greeter
  plan:
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
      run:
        path: /bin/ash
        args:
        - -e
        - -c
        - |
          echo "Well, hello there!"
