---
resource_types:
- name: concourse-pipelines-resource
  type: docker-image
  source:
    repository: paroxp/concourse-pipelines-resource
    tag: 0.0.1537562405

resources:
- name: gsp-teams
  type: git
  source:
    uri: https://github.com/alphagov/gsp-teams.git
    branch: develop

- name: concourse-pipelines
  type: concourse-pipelines-resource
  source:
    username: ((concourse.username))
    password: ((concourse.password))
    target: http://concourse-web:8080
    insecure: true

jobs:
- name: setup-pipelines
  plan:
  - get: gsp-teams
    trigger: true
  - task: compose-concourse-pipelines-list
    params:
      SETUP_PIPELINE_ACTION: updater
      SETUP_PIPELINE_TEAM_CONFIG: gsp-teams/teams/*.yaml
      SETUP_PIPELINE_TEAM_NAME: main
      SETUP_PIPELINE_PAUSED: true
      SETUP_PIPELINE_UPDATER_GROUP: true
    file: gsp-teams/ci/tasks/setup-pipelines/task.yaml
  - put: concourse-pipelines
