---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ci-deploy-key
data:
  private_key: "RklYTUUK"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ci-deploy-key
data:
  public_key: "RklYTUUK"
